quiz/urls.py
from django.urls import path
from quiz import views


app_name = 'quiz'
urlpatterns = [
    path('', views.quizhome, name='dashboard'),

        # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),
     # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/',
         views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),
    
    # /quiz/10/1/vote/
    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),

    # ex: /quiz/create/7/2/
    path('create/<int:quiz_id>/<int:question_id>/',
         views.create_question, name='create_question'),
]

schoolauthquiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('quiz/', include('quiz.urls'))
]

quiz/models.py
from django.db import models


# Create your models here.
class Quiz(models.Model):
    quiz_title = models.CharField(max_length=300)
    num_questions = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.TextField(max_length=10000)
    question_num = models.IntegerField(default=0)
    answer = models.CharField(max_length=300)
    explanation = models.TextField(max_length=5000)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return str(self.choice_text)

quiz/forms.py
from django import forms

from django.core.exceptions import ValidationError

from django.utils.translation import ugettext_lazy as _

# form to create a new quiz


class CreateQuizForm(forms.Form):
    quiz_name = forms.CharField(max_length=50, label="Quiz Name", widget=forms.TextInput(
        attrs={'class': 'quiz_name_box'}))
    num_questions = forms.IntegerField(label="Number of Questions", widget=forms.NumberInput(
        attrs={'class': 'num_questions_box'}))

    def clean_name(self):
        data = self.cleaned_data['quiz_name']

        # Check if quiz name is unique.
        if data == "Default_Name":
            raise ValidationError(_('Invalid name - Must be Unique'))

        # returns cleaned data
        return data

    def clean_num_questions(self):
        data = self.cleaned_data['num_questions']

        # Check if number of questions is at least 1 and is an integer
        if (isinstance(data, int) == False) or (data < 1):
            raise ValidationError(
                _('Invalid number - must be positive integer'))

        # Remember to always return the cleaned data.
        return data


# form to create questions with choices for each quiz
class CreateQuestionForm(forms.Form):
    question_text = forms.CharField(max_length=10000, label="Question Text", widget=forms.TextInput(
        attrs={'class': 'question_text_box'}))

    choice1_text = forms.CharField(max_length=10000, label="Choice 1", widget=forms.TextInput(
        attrs={'class': 'choice_box'}))
    choice1_correctness = forms.BooleanField(
        label="Choice 1 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice2_text = forms.CharField(
        max_length=10000, label="Choice 2", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice2_correctness = forms.BooleanField(
        label="Choice 2 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice3_text = forms.CharField(
        max_length=10000, label="Choice 3", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice3_correctness = forms.BooleanField(
        label="Choice 3 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice4_text = forms.CharField(
        max_length=10000, label="Choice 4", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice4_correctness = forms.BooleanField(
        label="Choice 4 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    explanation = forms.CharField(max_length=10000, label="Explanation Text", widget=forms.TextInput(
        attrs={'class': 'explanation_text_box'}))

    answer = forms.CharField(max_length=10000, label="answer", widget=forms.TextInput(
        attrs={'class': 'answer_text_box'}))

    # makes sure that exactly one answer is selected to be true

    def clean(self):

        choice1_answer = self.cleaned_data["choice1_correctness"]
        choice2_answer = self.cleaned_data["choice2_correctness"]
        choice3_answer = self.cleaned_data["choice3_correctness"]
        choice4_answer = self.cleaned_data["choice4_correctness"]

        answer_list = [choice1_answer, choice2_answer,
                       choice3_answer, choice4_answer]

        print(answer_list)

        trueCount = 0
        for ans in answer_list:
            if ans == True:
                trueCount += 1

        if trueCount != 1:
            raise ValidationError(_('Must have exactly one correct answer'))

        return self.cleaned_data

quiz/views.py
from datetime import *
import time
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from quiz.forms import CreateQuizForm
from django.shortcuts import redirect, render
from quiz.models import Question, Quiz
# from quiz.forms import QuestionForm
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from quiz.models import Quiz, Question, Choice

from quiz.forms import CreateQuizForm, CreateQuestionForm
from datetime import datetime, time
import datetime
from django.utils import timezone
from django.contrib import messages


def quizhome(request):
    all_quiz_list = Quiz.objects.all()
    context = {
        'all_quiz_list': all_quiz_list,
    }

    return render(request, 'quiz/index.html', context)

# specific quiz splash screen


def single_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_questions = len(quiz.question_set.all())

    # deletes quiz and returns to home if no questions created
    if num_questions == 0:
        quiz.delete()
        all_quiz_list = Quiz.objects.all()
        context = {
            'all_quiz_list': all_quiz_list,
        }
        return render(request, 'quiz/index.html', context)

    quiz.num_questions = num_questions
    quiz.save()
    messages.success(request, f'Hi ,Your {quiz} Open successfully !')

    # resets accuracy info to 0
    request.session["num_correct"] = 0
    request.session["num_wrong"] = 0

    context = {
        'quiz': quiz,
        'num_questions': num_questions,
    }

    return render(request, 'quiz/single_quiz.html', context)


# specific question view
def single_question(request, quiz_id, question_id):
    time = timezone.now()  # Time like '23:12:05'%H:%M:%S'

    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)

    # Checks if currently on last question of quiz
    next_or_submit = "Next"
    last_question_check = False
    if question_id == (len(quiz.question_set.all())):
        last_question_check = True
        next_or_submit = "Submit"

    next_question_id = question_id+1

    all_choices = current_question.choice_set.all()
    print(all_choices,)

    context = {
        'current_question': current_question,
        'all_choices': all_choices,
        'quiz': quiz,
        'next_question_id': next_question_id,
        'last_question_check': last_question_check,
        'next_or_submit': next_or_submit,
        'time': time,
    }

    return render(request, 'quiz/single_question.html', context)


# view that receives info from user's answer to question and determines correctness


def vote(request, quiz_id, question_id):

    start_time = datetime.datetime.now()

    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)

    # checks if current question is last one
    next_or_submit = "Next"
    if question_id == (len(quiz.question_set.all())):
        next_or_submit = "Submit"

        # messages.success(
        #     request,  f'Hi ,Your {current_question}  complated successfully !')

    try:
        selected_choice = current_question.choice_set.get(
            pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'quiz/single_question.html', {
            'quiz': quiz,
            'current_question': current_question,
            'error_message': "You didn't select a choice.",
            'next_or_submit': next_or_submit,
            # 'message':message,
        })
    else:

        # get which choice is the correct answer
        correct_answer = current_question.choice_set.get(correct=True)

        if selected_choice == correct_answer:
            # if request.session["num_correct"]:

            print("You are right", selected_choice)
            request.session["num_correct"] += 1
            messages.success(
                request, f'{question_id,selected_choice} answer is right !')
        else:
            print("You are wrong", selected_choice)
            request.session["num_wrong"] += 1
            messages.warning(
                request, f'{question_id,selected_choice} answer is wrong !')

        # checks if next page should be results or next question
        if question_id == (len(quiz.question_set.all())):
            if "Submit":
                # do your work here
                end_time = datetime.datetime.now()
                global Taketime
                Taketime = end_time - start_time
                print('Duration: {}'.format(end_time - start_time))
            return HttpResponseRedirect(reverse('quiz:results', args=(quiz.id,)))
        else:

            return HttpResponseRedirect(reverse('quiz:single_question', args=(quiz.id, question_id+1,)))


# quiz results page
def results(request, quiz_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id)
    global num_correct
    global num_wrong

    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]

    if num_correct:
        messages.success(request, ' answer is Right !')
    if num_wrong:
        messages.warning(request, ' answer is wrong !')

    total_questions = num_correct+num_wrong

    # formats accuracy as % with no decimal digits
    # try:
    # global accuracy
    # while True:
    if total_questions != 0:
        accuracy = num_correct/(total_questions)
        accuracy_over_75 = False
        if accuracy >= .75:
            accuracy_over_75 = True

        accuracy_formatted = "{:.0%}".format(accuracy)

    # print('cant be divided')
    # ZeroDivisionError: division by zero

    # except (ZeroDivisionError, UnboundLocalError, NameError):

    return render(request, 'quiz/results.html', {
        'num_correct': num_correct,
        'num_wrong': num_wrong,
        'Taketime': Taketime,
        'accuracy_over_75': accuracy_over_75,
        'accuracy_formatted': accuracy_formatted,
        'total_questions': total_questions,
        'quiz': quiz,
    })


# view for create quiz page
def create_quiz(request):

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuizForm(request.POST or None)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            quiz_name = form.cleaned_data['quiz_name']
            num_questions = form.cleaned_data['num_questions']

            new_quiz = Quiz(quiz_title=quiz_name, num_questions=num_questions)
            new_quiz.save()

            # return redirect('dashboard')

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('quiz:create_question', args=(new_quiz.id, 1,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuizForm()

    context = {
        'form': form,
    }

    return render(request, 'quiz/create_quiz.html', context)


# # view for create quiz page
def create_question(request, quiz_id, question_id):

    # gets current quiz
    quiz = Quiz.objects.get(pk=quiz_id)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuestionForm(request.POST or None)

        # Check if the form is valid:
        if form.is_valid():

            # process the data in form.cleaned_data as required
            question_text = form.cleaned_data['question_text']
            answer = form.cleaned_data['answer']
            explanation = form.cleaned_data['explanation']
            print(explanation)
            print(answer)
            choice1 = form.cleaned_data["choice1_text"]
            choice1_correctness = form.cleaned_data["choice1_correctness"]

            choice2 = form.cleaned_data["choice2_text"]
            choice2_correctness = form.cleaned_data["choice2_correctness"]

            choice3 = form.cleaned_data["choice3_text"]
            choice3_correctness = form.cleaned_data["choice3_correctness"]

            choice4 = form.cleaned_data["choice4_text"]
            choice4_correctness = form.cleaned_data["choice4_correctness"]

            # creates question in quiz
            question = Question(
                quiz=quiz, question_text=question_text, answer=answer, explanation=explanation, question_num=question_id)
            question.save()

            # creates choices for questions
            question.choice_set.create(
                choice_text=choice1, correct=choice1_correctness)
            question.choice_set.create(
                choice_text=choice2, correct=choice2_correctness)
            question.choice_set.create(
                choice_text=choice3, correct=choice3_correctness)
            question.choice_set.create(
                choice_text=choice4, correct=choice4_correctness)

            # redirect to home if done or next create question page if not
            if question_id == quiz.num_questions:
                return HttpResponseRedirect(reverse('quiz:dashboard'))
            else:
                return HttpResponseRedirect(reverse('quiz:create_question', args=(quiz_id, question_id+1,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuestionForm()

    if question_id == quiz.num_questions:
        next_submit = "Submit"
    else:
        next_submit = "Next"

    context = {
        'form': form,
        'question_num': question_id,
        'next_submit': next_submit,

    }

    return render(request, 'quiz/create_question.html', context)


#

templates/quiz/create_quiz.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
  body {
    margin: 0;
    padding: 0;
    background-color: #17a2b8;
    height: 100vh;
  }

  #login .container #login-row #login-column #login-box {
    margin-top: 60px;
    max-width: 600px;
    height: 320px;
    border: 1px solid #9C9C9C;
    background-color: #EAEAEA;
  }

  #login .container #login-row #login-column #login-box #login-form {
    padding: 20px;
  }
</style>

<div id="login">
  <h3 class="text-center text-white pt-5">Create Quiz Form</h3>
  <div class="container">
    <div id="login-row" class="row justify-content-center align-items-center">
      <div id="login-column" class="col-md-6">
        <div id="login-box" class="col-md-12">

          <form id="login-form" class="form" action="" method="post">

            {% csrf_token %}
            <h3 class="text-center text-info">Create Quiz</h3>

            <div class="form-group">

              {{ form|crispy }}
            </div>
            <div class="form-group">
              <!-- <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br> -->
              <input type="submit" name="submit" class="btn btn-info btn-md" value="Create">
            </div>

          </form>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/quiz/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- //Note: This is for version 3.5.0. You can change it here \/ -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
    integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"> -->

{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-12 col-md-12">
            <h1 class="site_title">Quiz like Application</h1>
            <p class="site_description">Take a quiz or create your own!</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-lg-12 col-md-12">
            {% if all_quiz_list %}

            <section id="content" class="card_container">

                {% for quiz in all_quiz_list %}

                <div class="card text-white bg-primary sm-3 lg-3 mb-3"
                    style="max-width:100rem; min-width: 10rem;  margin:2px;">
                    <div class="card-header">{{ quiz.quiz_title }}</div>
                    <div class="card-body" style="text-align: justify; text-align: center;">
                        <h5 class="card-title">{{ quiz.num_questions }} Questions</h5>
                        <a class="btn btn-primary btn-lg" href="{% url 'quiz:single_quiz' quiz.id %}"
                            role="button">Start</a>

                    </div>
                </div>

                {% endfor %}
            </section>

            {% else %}
            <p>No quizzes are available.</p>
            {% endif %}

        </div>
    </div>

    {% else %}
    <!-- <div class="container"> -->
    <div class="row">
        <div class="col-6">
            <h2> Ohoooo Please login or Register.........!</h2>
        </div>
    </div>
    <!-- </div> -->
</div>
{% endif %}

{% endblock content %}

templates/quiz/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/quiz/results.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} 
{% load static %}
{%block content %} 
<style>
  body {
    margin: 0;
    padding: 0;
    background-color: #17a2b8;
    height: 100vh;
  }

  #login .container #login-row #login-column #login-box {
    margin-top: 1px;
    max-width: 600px;
    height: 30pc;
    border: 1px solid #9c9c9c;
    background-color: #eaeaea;
  }

  #login .container #login-row #login-column #login-box #login-form {
    padding: 20px;
  }

  #register-link {
    margin-top: -40px;
  }
</style>

<div id="login">
  <h3 class="text-center text-white pt-5">Results</h3>
  <div class="container">
    <div id="login-row" class="row justify-content-center align-items-center">
      <div id="login-column" class="col-md-6">
        <div id="login-box" class="col-md-12">
          <form id="login-form" class="form" action="" method="post">
            <h3 class="text-center text-info">Hello,{{user.username}}</h3>
            <br />
            <br />
            <div class="form-group">
              <label class="text-info">Total Questions:</label>
              <label class="text"> {{total_questions}} Questions </label><br />
            </div>

            <div class="form-group">
              <label class="text-info">No.Of. Q. Correct:</label>
              <label class="text"> {{num_correct}} </label><br />
            </div>
            <div class="form-group">
              <label class="text-info">No.Of .Q Wrong:</label>
              <label class="text"> {{num_wrong}} </label><br />
            </div>
            <div class="form-group">
              <label for="username" class="text-info">Score:</label>

              <label for="username" class="text">
                {% if accuracy_over_75 %}
                <p class="accuracy_good">{{ accuracy_formatted }}</p>

                {% else %}
                <p class="accuracy_bad">{{ accuracy_formatted }}</p>
                {% endif %}
              </label>
            </div>

            <div class="form-group">
              <label class="text-info">Time Taken:{{Taketime}} seconds</label>
            </div>

            <div class="text-left">
              <button type="button" class="btn btn-outline-info">
                <a
                  class="home_button"
                  style="text-decoration: none"
                  href="{% url 'quiz:dashboard' %}"
                  >Home</a
                >
              </button>
            </div>
            <div id="register-link" class="text-right">
              <button type="button" class="btn btn-outline-info">
                <a
                  class="home_button"
                  style="text-decoration: none; margin-top: 10px"
                  href="{% url 'quiz:single_quiz' quiz.id %}"
                  >Try Again</a
                >
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/quiz/single_question.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">



<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        background-color: #007bff;
    }

    .container {
        background-color: #007bff;
        color: #ddd;
        border-radius: 10px;
        padding: 20px;
        font-family: 'Montserrat', sans-serif;
        max-width: 700px
    }

    .container>p {
        font-size: 32px
    }

    .question {
        width: 75%
    }

    .options {
        position: relative;
        padding-left: 40px
    }

    #options label {
        display: block;
        margin-bottom: 15px;
        font-size: 14px;
        cursor: pointer
    }

    .options input {
        opacity: 0
    }

    .checkmark {
        position: absolute;
        top: -1px;
        left: 0;
        height: 25px;
        width: 25px;
        background-color: #007bff;
        border: 1px solid #ddd;
        border-radius: 50%;
    }

    .options input:checked~.checkmark:after {
        display: block;
    }

    .options .checkmark:after {
        content: "";
        width: 10px;
        height: 10px;
        display: block;
        /* background: white; */
        position: absolute;
        top: 50%;
        left: 50%;
        border-radius: 50%;
        transform: translate(-50%, -50%) scale(0);
        transition: 300ms ease-in-out 0s
    }

    .options input[type="radio"]:checked~.checkmark {
        background: #21bf73;
        transition: 300ms ease-in-out 0s
    }

    .options input[type="radio"]:checked~.checkmark:after {
        transform: translate(-50%, -50%) scale(1)
    }

    .btn-primary {
        background-color: #007bff;
        color: #ddd;
        border: 1px solid #ddd
    }

    .btn-primary:hover {
        background-color: #21bf73;
        border: 1px solid #21bf73
    }

    .btn-success {
        padding: 5px 25px;
        background-color: #21bf73
    }

    @media(max-width:576px) {
        .question {
            width: 100%;
            word-spacing: 2px;
        }
    }


    #clock {
        width: 40pc;
        margin-top: 13px;
        text-align: center;
        font-size: 15px;
    }
    .accordion-button{
        background-color: #007bff;
        color: white;
        border-collapse: collapse;
    }
    .accordion-body {
        background-color:white;
        color:#007bff;
        
    }
    #quest{
        margin-left: 40px;
        font-style: bold;
        font-size: 15px;
        font-family: 'Cuprum', sans-serif;
        font-family: 'Spectral', serif;
    }
    #box{
        width:90%;
        margin-top: 40px;

    }

    .options{
        color:white;
    }

</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cuprum&family=Spectral:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<title>Single Question</title>

<!--my code -->

<div class="container" id="box">
 
    <h2 style="text-align: center;">{{ quiz.quiz_title }}</h2>
    <div align="right "  > Timer:<span id="clock" ></span> </div>

    <!-- <input id="timer" type='hidden' name="timer" value=""> -->
    <input id="clock" type='hidden' name="clock" value=""> 
    <form action="{% url 'quiz:vote' quiz.id current_question.question_num %}" method="post">
        {% csrf_token %}
        <div class="container mt-sm-5 my-1">
            <div class="question ml-sm-5 pl-sm-5 pt-2">
                <div class="py-2 h5" id="quest"><b>Q.{{ current_question.question_text }}?</b></div>
           

                <div class="ml-md-3 ml-sm-3 pl-md-5 pt-sm-0 pt-3" id="options">
                    {% for choice in current_question.choice_set.all %}

                  <div class="row"  >
            
                
                      <div class="col">
                        <label for="choice{{ forloop.counter }}" class="options" > {{ choice.choice_text }}
                            <input style="display:none" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }} " onclick="showdata();">
                            <!-- <input  type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.choice_text }}" onclick="showdata();"> -->
                            <span class="checkmark"></span>
                        </label>
                      </div>
                      
                  </div>

                  <div>
                 
                  </div>

                    {% endfor %}
                </div>



                <div class="d-flex align-items-center pt-3">
                    
                    <div class="ml-auto mr-sm-5">

                        <input type="submit" id="btn" class="btn btn-primary lg submit_button" value={{ next_or_submit }}>
                    </div>

                </div>
            </div>
        </div>
    </form>


    <div class="accordion accordion-flush" id="accordionFlushExample">
        <!-- <div class="row"> -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseOne"  aria-expanded="false" aria-controls="flush-collapseOne">
                        Correct Answer
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                    data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body" id="correct" >{{ current_question.answer }} </div>
                </div>
            </div>
        <!-- </div>

        <div class="row"> -->
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                        Explanation
                    </button>
                </h2>
                <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo"
                    data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body" id="ex">{{ current_question.explanation}}</div>
                </div>
            </div>
        <!-- </div> -->

    </div>
</div>

<script>


// alert('{{ message }}');
// const fewSeconds = 3
 
//  document.querySelector('#btn').addEventListener('click', (e) => {
//      e.target.disabled = true
//    setTimeout(() => {
//     e.target.disabled = false
//    }, fewSeconds * 1000)
//  })

    setInterval(displayclock,500);
    function displayclock(){
        var time=new Date();
        var hrs=time.getHours();
        var min=time.getMinutes();
        var sec=time.getSeconds();
        var en='AM';
      
        if (hrs>12){
            en='PM';
        }
        if (hrs>12){
            hrs=hrs-12;
        }
        if (hrs==0){
            hrs=12;
        }

        if (hrs< 10){
            hrs='0' + hrs;
        }
        if (min< 10){
            min='0' + min;
        }
        if (sec< 10){
            sec='0' + sec;
        }

      var  an=document.getElementById('clock').innerHTML=hrs+':'+min+':'+sec+ ''+en;

        console.log(an)

    }
</script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



<script>


 </script>
 <script>
    $(document).ready(function () {
        $('.show').click(function () {
            $('.menu').toggle("slide");
        });
    });
 </script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
{% endblock content %}