quiz/urls.py
from django.urls import path
from quiz import views


app_name = 'quiz'
urlpatterns = [
    path('', views.quizhome, name='dashboard'),

        # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),
     # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/',
         views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),
    
    # /quiz/10/1/vote/
    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),

    # ex: /quiz/create/7/2/
    path('create/<int:quiz_id>/<int:question_id>/',
         views.create_question, name='create_question'),
]

schoolauthquiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('quiz/', include('quiz.urls'))
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cuprum&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      font-family: 'Cuprum', sans-serif;
    }
  </style>
</head>

<body id="bg" style=" background-image: url('{% static 'users/images/home.jpg' %}');">

  {% load static %}

  <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">School</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quiz:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quiz:create_quiz' %}">Create Quiz</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Hello, {{request.user}}</a>
          </li>

          {% endif %}
        </ul>
      </div>
  
    </div>
   </nav>

   {% block home %}
   <div class="sticky-top">
    {% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} m-2">{{message}}</div>
    {% endfor %}
    {% endif %}
  </div>

   {% endblock %}
   <div class="container">
    {% block content %}
    <div class="sticky-top">
      {% if messages %}
      {% for message in messages %}
      <div class="alert {{ message.tags }} m-2">{{message}}</div>
      {% endfor %}
      {% endif %}
    </div>
    {% endblock %}


  </div>
</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>